[package]
authors     = ["magic-akari <akari.ccino@gmail.com>"]
description = "A WASM based Markdown Formatter"
edition     = "2024"
homepage    = "https://github.com/wasm-fmt/markdown"
keywords    = ["wasm", "markdown", "formatter"]
license     = "MIT OR Apache-2.0"
name        = "markdown"
readme      = "README.md"
repository  = "https://github.com/wasm-fmt/markdown"
version     = "0.1.6"


[dependencies]
bridge                 = { package = "wasm-fmt-fdk", version = "=0.0.1", features = ["host-formatting"] }
dprint-core            = "0.67.4"
dprint-plugin-markdown = "0.22.0"
serde_json             = "1"

[dev-dependencies]
dprint-development = "0.12.0"
serde_json         = "1"


[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
codegen-units = 1
debug         = false
lto           = true
opt-level     = 2
panic         = "abort"
strip         = "symbols"

[[test]]
harness = false
name    = "specs"
path    = "tests/spec_test.rs"

[patch.crates-io]
regex = { path = "crates/regex_patch" }
